### ISSUE TITLE
con.exportStatement() generates syntactically incorrect CONSTRUCT query

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#108]
testWriterCon.exportStatements(null, null, null, false, new RDFHandlerBase() {
			@Override
			public void handleStatement(Statement st)
				throws RDFHandlerException
			{
				assertThat(st, is(not(equalTo(st1))));
			}
		});

The above con.exportStatements()  generates syntactically incorrect CONSTRUCT query
"CONSTRUCT {?s ?p ?o} WHERE {GRAPH <http://marklogic.com/dirgraph> {?s ?p  .} }"

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at /graphs/sparql: Bad Request. Server Message: XDMP-UNEXPECTED: (err:XPST0003) Unexpected token syntax error, unexpected .
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4598)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3492)
	at com.marklogic.client.impl.JerseyServices.executeSparql(JerseyServices.java:5606)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeQueryImpl(SPARQLQueryManagerImpl.java:101)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeQueryImpl(SPARQLQueryManagerImpl.java:94)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeDescribe(SPARQLQueryManagerImpl.java:129)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performGraphQuery(MarkLogicClientImpl.java:204)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performGraphQuery(MarkLogicClientImpl.java:185)
	at com.marklogic.semantics.sesame.client.MarkLogicClient.sendGraphQuery(MarkLogicClient.java:101)
	at com.marklogic.semantics.sesame.query.MarkLogicGraphQuery.evaluate(MarkLogicGraphQuery.java:53)
	at com.marklogic.semantics.sesame.query.MarkLogicGraphQuery.evaluate(MarkLogicGraphQuery.java:60)
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.exportStatements(MarkLogicRepositoryConnection.java:401)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testInsertRemove(MarkLogicRepositoryConnectionTest.java:1174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by xquery** [comment]
fix is in PR #161 out to review

**Comment by srinathgit** [comment]
The following statement still generates an invalid SPARQL query. It generates "CONSTRUCT {?s ?p ?o} WHERE {?s ?p  }"

		testWriterCon.exportStatements(null, null, null, false, new RDFHandlerBase() {

			@Override
			public void handleStatement(Statement st)
				throws RDFHandlerException
			{
				assertThat(st, is(not(equalTo(st1))));
			}
		});

**Comment by xquery** [comment]
nice catch ... my own unit test assert was not strong enough to catch this variant, should be easy to fix.

**Comment by xquery** [comment]
actually I applied the fix in the wrong place ... fixed, pls retest and give me a shout if you encounter any issues.

**Comment by srinathgit** [comment]
The fix works fine.
