### ISSUE TITLE
Handling 'null' results in SPARQL query output

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#109]
If a null is returned is from sparql query output, in marklogic-seame , <"null"^^<http://www.w3.org/2001/XMLSchema#anySimpleType> is returned. Is this expected or should it return a java null literal  or something different in Sesame ?

**Comment by grechaw** [comment]
There's no such thing as null in RDF, so I wonder where this is coming from.  It would help to see the JSON sparql results in other words.

**Comment by srinathgit** [comment]
Charles,
I think I should have phrased the "Bug Statement" better. I was talking about the scenario where the variables in the SPARQL query don't have a value bound to them. For instance , in the query below  the value of ?m is null. The value returned for the 'm'  in seseame-marklogic is <"null"^^http://www.w3.org/2001/XMLSchema#anySimpleType. I wanted to know if this is expected or should it return a java null literal or something different .
Query:
SELECT ?s ?p ?o ?m
{ ?s ?p ?o.
}

**Comment by xquery** [comment]
this is not expected and its on my radar, nice catch

**Comment by xquery** [comment]
I was unable to replicate, you sure you did not have a string "null" ?

**Comment by srinathgit** [comment]
Yes, we return a string of value "null" when a variable is not bound to a value.The problem is I want to return values of a field which is of type 'double'. There are two output records one of which is say 222D and other is "null".  While iterating through result sets, when calling literal.doubleValue(), we return 222D correctly and when it comes to "null", an exception as seen below is thrown. I wanted to know if this is the standard way Sesame handles this issue as well and if not shouldn't the double value in case of "null", set as a null literal or something else .

java.lang.NumberFormatException: For input string: "null"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.openrdf.model.datatypes.XMLDatatypeUtil.parseDouble(XMLDatatypeUtil.java:1872)
	at org.openrdf.model.impl.LiteralImpl.doubleValue(LiteralImpl.java:266)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testPrepareTupleQuery4(MarkLogicRepositoryConnectionTest.java:755)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by xquery** [comment]
when I run a TupleQuery with

SELECT ?s ?p ?o ?m
{ ?s ?p ?o.
}

I get no error ... but there is an error there ... just in another thread pool.

```
Exception in thread "pool-2-thread-1" java.lang.IllegalArgumentException: Not a valid (absolute) URI: birth-year
	at org.openrdf.model.impl.URIImpl.setURIString(URIImpl.java:79)
	at org.openrdf.model.impl.URIImpl.<init>(URIImpl.java:68)
	at org.openrdf.model.impl.ValueFactoryImpl.createURI(ValueFactoryImpl.java:51)
	at org.openrdf.query.resultio.sparqljson.SPARQLJSONParserBase.parseValue(SPARQLJSONParserBase.java:378)
	at org.openrdf.query.resultio.sparqljson.SPARQLJSONParserBase.parseQueryResultInternal(SPARQLJSONParserBase.java:289)
	at org.openrdf.query.resultio.sparqljson.SPARQLJSONParserBase.parseQueryResult(SPARQLJSONParserBase.java:117)
	at org.openrdf.http.client.BackgroundTupleResult.run(BackgroundTupleResult.java:102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

because our results are generated with background worker.

This error we know about, as reported in issue #100 which is still open.

At a minimum we should be trapping this error so I will catch up with Charles whats the modern way of trapping errors in other threads.

**Comment by xquery** [comment]
I think my previous comment was just reporting on a variant of #100 

I am still unable to replicate getting a null returned as as SimpleType.

I observe when I hit the server 

```
http://localhost:8200/v1/graphs/sparql?query=SELECT ?s ?p ?o ?m { ?s ?p ?o.}
```
which has no triples I get;

```
{
  "head": {
    "vars": []
  },
  "results": {
    "bindings": []
  }
}
```

if there are any triples I see no null in the return

```
{
  "head": {
    "vars": [
      "s",
      "p",
      "o",
      "m"
    ]
  },
  "results": {
    "bindings": [
      {
        "s": {
          "type": "uri",
          "value": "http://test.org"
        },
        "p": {
          "type": "uri",
          "value": "http://www.example.org/johny"
        },
        "o": {
          "datatype": "http://www.w3.org/2001/XMLSchema#string",
          "type": "literal",
          "value": "test"
        }
      }
    ]
  }
}
```

sending a similar query via Sesame;

```
String queryString = "select ?s ?p ?o ?m { ?s ?p ?o } limit 1 ";
MarkLogicTupleQuery tupleQuery = conn.prepareTupleQuery(QueryLanguage.SPARQL, queryString);        
TupleQueryResult results = tupleQuery.evaluate();
```

yields the correct responses with no bindings with null. 

Can you supply me with example that generates this ?

**Comment by srinathgit** [comment]
Jim,

Can you have a look into the test 'testPrepareTupleQuery4'  ? There is no result as 'null' anymore but it yields no bindings. This causes issues which can be seen in the test.

**Comment by xquery** [comment]
ok I reviewed, this is expected as nothing is returned there will be no binding. I Think this is working as intended. If you think we need to do something differently, then pls hand the bug back to me.

**Comment by srinathgit** [comment]
Changed the test as per the intended behavior.

**Comment by xquery** [comment]
we may review this in vnext but yes confirming this is intended behavior.
