### ISSUE TITLE
Trying to unset Ruleset throws NullPointerException

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#163]
The following snippet throws NullPointerException
A) 
tupleQuery =  testAdminCon.prepareTupleQuery(QueryLanguage.SPARQL, query);
((MarkLogicQuery) tupleQuery).setRulesets(null);

Stacktrace:
java.lang.NullPointerException
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.setRulesets(MarkLogicClientImpl.java:374)
	at com.marklogic.semantics.sesame.client.MarkLogicClient.setRulesets(MarkLogicClient.java:348)
	at com.marklogic.semantics.sesame.query.MarkLogicQuery.setRulesets(MarkLogicQuery.java:268)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testRuleSets2(MarkLogicRepositoryConnectionTest.java:2753)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

B)
tupleQuery =  testAdminCon.prepareTupleQuery(QueryLanguage.SPARQL, query);
((MarkLogicQuery) tupleQuery).setRulesets((SPARQLRuleset)null);
tupleQuery.setIncludeInferred(false);
result = tupleQuery.evaluate();

Stacktrace:

java.lang.NullPointerException
	at com.marklogic.client.impl.JerseyServices.executeSparql(JerseyServices.java:5612)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeQueryImpl(SPARQLQueryManagerImpl.java:107)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeSelect(SPARQLQueryManagerImpl.java:79)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performSPARQLQuery(MarkLogicClientImpl.java:181)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performSPARQLQuery(MarkLogicClientImpl.java:162)
	at com.marklogic.semantics.sesame.client.MarkLogicClient.sendTupleQuery(MarkLogicClient.java:126)
	at com.marklogic.semantics.sesame.query.MarkLogicTupleQuery.evaluate(MarkLogicTupleQuery.java:76)
	at com.marklogic.semantics.sesame.query.MarkLogicTupleQuery.evaluate(MarkLogicTupleQuery.java:63)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testRuleSets2(MarkLogicRepositoryConnectionTest.java:2755)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by xquery** [comment]
fix in PR #164 out to review

**Comment by srinathgit** [comment]
I am not sure what this snippet means but it fails with NullPointerException as well. So should this setRulsesets(null,SPARQLRuleset.INVERSE_OF), set only INVERSE_OF ruleset ?

tupleQuery =  testAdminCon.prepareTupleQuery(QueryLanguage.SPARQL, query);
((MarkLogicQuery) tupleQuery).setRulesets(null,SPARQLRuleset.INVERSE_OF);
result = tupleQuery.evaluate();

**Comment by xquery** [comment]
the PR covers off that scenario as well eg. filters out nulls if they are intermixed.

**Comment by srinathgit** [comment]
What is the expected behavior of the following ?

Should the SPARQLRuleset.EQUIVALENT_PROPERTY be set ? The same question would also extend for testAdminCon.setDefaultRuleset()

((MarkLogicQuery) tupleQuery2).setRulesets(SPARQLRuleset.EQUIVALENT_PROPERTY, null);

**Comment by xquery** [comment]
generic handling of varargs with null is out of scope ... but in this instance I have created a filter which filters out any usage of null when setting rulesets.

I have not done a similar filter for default rulesets ... as an enhancement it sounds simple but the reality is I would have to do a little re-org in the client impl ... closing this and added #180

**Comment by srinathgit** [comment]
SO, if I understand correct, after the fix, the following test should be correct . Right now, it fails as rulset.length is 2

testAdminCon.setDefaultRulesets(SPARQLRuleset.EQUIVALENT_PROPERTY, null);
SPARQLRuleset [] ruleset = testAdminCon.getDefaultRulesets();
Assert.assertEquals(1, ruleset.length);

**Comment by xquery** [comment]
no, I filter out the rulesets when we apply them in context of query ... eg you 'see' what you set by default on the connetion (nulls and all) but under the covers in the MarkLogicClientImpl they get filtered.

For example you could set default rulesets on connection, create a query then somequery.getRulesets() should return rulesets minus nulls.

The handling of null was important in Sesame for handling Context as null= default graph, but not a priority to protect developers from themselves ... I've changed title of #180 and I would propose using that as a general bucket for null handling (outside of Context).

**Comment by srinathgit** [comment]
Thanks for the explanation. This one works fine..
