### ISSUE TITLE
Executing tuple query with base uri and bindings causes failure

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#197]
The following test named 'testPrepareTupleQuerywithBidings' in regression fails . The exception is provided below. The same query when run from queryconsole runs fine.

	@Test
	public void testPrepareTupleQuerywithBidings() throws Exception{
		
		Statement st1 = vf.createStatement(john, fname, johnfname, dirgraph);
		Statement st2 = vf.createStatement(john, lname, johnlname, dirgraph);
		Statement st3 = vf.createStatement(john, homeTel, johnhomeTel, dirgraph);
		Statement st4 = vf.createStatement(john, email, johnemail, dirgraph);
		Statement st5 = vf.createStatement(micah, fname, micahfname, dirgraph);
		Statement st6 = vf.createStatement(micah, lname, micahlname, dirgraph);
		Statement st7 = vf.createStatement(micah, homeTel, micahhomeTel, dirgraph);
		Statement st8 = vf.createStatement(fei, fname, feifname, dirgraph);
		Statement st9 = vf.createStatement(fei, lname, feilname, dirgraph);
		Statement st10 = vf.createStatement(fei, email, feiemail, dirgraph);
		
		testAdminCon.add(st1);
		testAdminCon.add(st2);
		testAdminCon.add(st3);
		testAdminCon.add(st4);
		testAdminCon.add(st5);
		testAdminCon.add(st6);
		testAdminCon.add(st7);
		testAdminCon.add(st8);
		testAdminCon.add(st9);
		testAdminCon.add(st10);
		
				
		try{
			Assert.assertEquals(10, testAdminCon.size(dirgraph));
		}
		catch(Exception ex){
			logger.error("Failed :", ex);
		}
			
		
		StringBuilder queryBuilder = new StringBuilder(64);
		
		queryBuilder.append(" SELECT ?person ?firstname ?lastname ?phonenumber");
		queryBuilder.append(" FROM <").append(dirgraph.stringValue()).append(">");
		queryBuilder.append(" WHERE");
		queryBuilder.append(" { ");
		queryBuilder.append("   ?person <#firstName> ?firstname ;");
		queryBuilder.append("           <#lastName> ?lastname ; ");
		queryBuilder.append("           <#homeTel> ?phonenumber .} ");
		queryBuilder.append(" ORDER BY ?lastname");
		
		TupleQuery query = testAdminCon.prepareTupleQuery(queryBuilder.toString(),"http://marklogicsparql.com/addressbook");
		query.setBinding("firstname", vf.createLiteral("Micah"));
		
		TupleQueryResult result = query.evaluate();
		
		String [] epectedPersonresult = {"http://marklogicsparql.com/id#2222"};
		String [] expectedLnameresult = {"Dubinko"};
		String [] expectedFnameresult = {"Micah"};
		int i = 0;
		try {
			assertThat(result, is(notNullValue()));
			Assert.assertTrue(result.hasNext());
			while (result.hasNext()) {
				BindingSet solution = result.next();
				assertThat(solution.hasBinding("person"), is(equalTo(true)));
				assertThat(solution.hasBinding("lastname"), is(equalTo(true)));
				Value personResult = solution.getValue("person");
				Value lnameResult = solution.getValue("lastname");
				Value fnameResult = solution.getValue("firstname");
				Literal phoneResult = (Literal) solution.getValue("phonenumber");		
				Assert.assertEquals(epectedPersonresult[i], personResult.stringValue());
				Assert.assertEquals(expectedLnameresult[i], lnameResult.stringValue());
				Assert.assertEquals(expectedFnameresult[i], fnameResult.stringValue());
				assertThat(phoneResult.doubleValue(),  is(equalTo(new  Double(22222222D))));
				i++;
			}
		}
		finally {
			result.close();
		}
	
	}

org.openrdf.query.QueryEvaluationException: Local message: failed to apply resource at /graphs/sparql: Internal Server Error. Server Message: XDMP-SPQLBOUND: Variable value supplied by the calling environment: firstname . See the MarkLogic server error log for further detail.
	at com.marklogic.semantics.sesame.query.MarkLogicTupleQuery.evaluate(MarkLogicTupleQuery.java:89)
	at com.marklogic.semantics.sesame.query.MarkLogicTupleQuery.evaluate(MarkLogicTupleQuery.java:67)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testPrepareTupleQuerywithBidings(MarkLogicRepositoryConnectionTest.java:845)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.marklogic.client.FailedRequestException: Local message: failed to apply resource at /graphs/sparql: Internal Server Error. Server Message: XDMP-SPQLBOUND: Variable value supplied by the calling environment: firstname . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4610)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3493)
	at com.marklogic.client.impl.JerseyServices.executeSparql(JerseyServices.java:5619)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeQueryImpl(SPARQLQueryManagerImpl.java:107)
	at com.marklogic.client.impl.SPARQLQueryManagerImpl.executeSelect(SPARQLQueryManagerImpl.java:79)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performSPARQLQuery(MarkLogicClientImpl.java:157)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performSPARQLQuery(MarkLogicClientImpl.java:127)
	at com.marklogic.semantics.sesame.client.MarkLogicClient.sendTupleQuery(MarkLogicClient.java:173)
	at com.marklogic.semantics.sesame.query.MarkLogicTupleQuery.evaluate(MarkLogicTupleQuery.java:81)
	... 29 more

**Comment by xquery** [comment]
can you retest using latest server (or confirm thats what you did ?)

**Comment by srinathgit** [comment]
1.. Can you try running the test 'testPrepareTupleQuerywithBidings' with the latest server build 
2. The base uri is provided as an argument in the 'prepareTupleQuery' method.

testAdminCon.prepareTupleQuery(queryBuilder.toString(),"http://marklogicsparql.com/addressbook");

**Comment by xquery** [comment]
ok will attempt ... need new eyeglasses I see, completely missed setting of base uri thanks for pointing it out.

**Comment by xquery** [comment]
I thought at first that your query could be malformed (ex. ?lastname.) but now when I run this it passes for me with latest.

**Comment by xquery** [comment]
PR #207 out to review

**Comment by xquery** [comment]
turns out I was setting bindings twice in certain circumstances ... this should fix it.

**Comment by srinathgit** [comment]
Query runs fine now.
