### ISSUE TITLE
exportStatements method called on empty store throws NullPointerException

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#250]
exportStatements method called on empty store throws NullPointerException

Code:
```
	@Test
	public final void testInsertRemove()
		throws OpenRDFException
	{
		Assert.assertEquals(0L, testAdminCon.size());
		testAdminCon.exportStatements(null, null, null, false, new RDFHandlerBase() {

			@Override
			public void handleStatement(Statement st1)
				throws RDFHandlerException
			{
				assertThat(st1, is((equalTo(null))));
			}
		},dirgraph);
	}
```

Exception:

```
java.lang.NullPointerException
	at org.openrdf.http.client.BackgroundGraphResult.handleClose(BackgroundGraphResult.java:106)
	at info.aduna.iteration.CloseableIterationBase.close(CloseableIterationBase.java:65)
	at org.openrdf.query.QueryResults.report(QueryResults.java:199)
	at com.marklogic.semantics.sesame.query.MarkLogicGraphQuery.evaluate(MarkLogicGraphQuery.java:85)
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.exportStatements(MarkLogicRepositoryConnection.java:780)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testInsertRemove(MarkLogicRepositoryConnectionTest.java:1680)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by srinathgit** [comment]
NPE is no longer thrown.
