### ISSUE TITLE
"Task already scheduled or cancelled" error with multiple concurrent users

### ISSUE THREAD

**Issue by cmatheus** [marklogic/marklogic-sesame#251]
we brought up this issue last week and thought it had gone away when we built the latest code from the develop branch (MD5 (marklogic-sesame-1.0.0-SNAPSHOT.jar) = e561c13de53923e5d4d8b4a6c1b8986f)
but that didn't actually fix the problem.

our code works fine with a single user but when we increase that to 10 concurrent users the "Task already scheduled or cancelled" error occasionally occurs - 70 ties out of 1000 in the test below.  the endpoint being hit makes a SPARQL query over a sesame connection to MarkLogic 8.0-4.2.

ApacheBench test results
==================
The following is a small test of 10 concurrent users, with a 1000 requests total:

$ ab -n 1000 -c 10 http://localhost:8080/api/v2/search
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests

Server Software:        Apache-Coyote/1.1
Server Hostname:        localhost
Server Port:            8080

Document Path:          /api/v2/search
Document Length:        0 bytes

Concurrency Level:      10
Time taken for tests:   10.305 seconds
Complete requests:      1000
Failed requests:        930
   (Connect: 0, Receive: 0, Length: 930, Exceptions: 0)
**Non-2xx responses:      70**
Total transferred:      794230 bytes
HTML transferred:       627750 bytes
Requests per second:    97.04 [#/sec] (mean)
Time per request:       103.052 [ms] (mean)
Time per request:       10.305 [ms] (mean, across all concurrent requests)
Transfer rate:          75.26 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:    34  102  31.8     99     355
Waiting:       34  102  31.7     99     355
Total:         34  103  31.7    100     355

Percentage of the requests served within a certain time (ms)
  50%    100
  66%    110
  75%    117
  80%    122
  90%    140
  95%    153
  98%    175
  99%    204
 100%    355 (longest request)

Server stats
===============================

This is the reported stats from the server.   Note that the count of 70 for counter.status.500.api.v2.search matches the AB report.
{
mem: 1795664,
mem.free: 1091084,
processors: 8,
instance.uptime: 633202,
uptime: 646245,
systemload.average: 2.71240234375,
heap.committed: 1692160,
heap.init: 262144,
heap.used: 601075,
heap: 3728384,
nonheap.committed: 105152,
nonheap.init: 2496,
nonheap.used: 103493,
nonheap: 0,
threads.peak: 59,
threads.daemon: 25,
threads.totalStarted: 2049,
threads: 27,
classes: 11644,
classes.loaded: 11644,
classes.unloaded: 0,
gc.ps_scavenge.count: 18,
gc.ps_scavenge.time: 219,
gc.ps_marksweep.count: 3,
gc.ps_marksweep.time: 600,
httpsessions.max: -1,
httpsessions.active: 0,
gauge.response.api.v2.search: 61,
gauge.response.metrics: 1,
gauge.response.star-star.favicon.ico: 3,
counter.status.200.star-star.favicon.ico: 11,
counter.status.200.metrics: 10,
counter.status.200.api.v2.search: 1944,
**counter.status.500.api.v2.search: 70**
}

stack trace
==============================
2016-03-03 14:21:45.865 ERROR 56739 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.getConnection' defined in class path resource [com/bericotechnologies/imc/rest/config/marklogic/MarkLogicRepositoryContext.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.openrdf.repository.RepositoryConnection]: Factory method 'getConnection' threw exception; nested exception is java.lang.IllegalStateException: Task already scheduled or cancelled] with root cause

java.lang.IllegalStateException: Task already scheduled or cancelled
at java.util.Timer.sched(Timer.java:401) ~[na:1.8.0_51]
at java.util.Timer.scheduleAtFixedRate(Timer.java:328) ~[na:1.8.0_51]
at com.marklogic.semantics.sesame.client.MarkLogicClient.initTimer(MarkLogicClient.java:114) ~[marklogic-sesame-1.0.0-SNAPSHOT.jar!/:na]
at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.<init>(MarkLogicRepositoryConnection.java:101) ~[marklogic-sesame-1.0.0-SNAPSHOT.jar!/:na]
at com.marklogic.semantics.sesame.MarkLogicRepository.getConnection(MarkLogicRepository.java:201) ~[marklogic-sesame-1.0.0-SNAPSHOT.jar!/:na]
at com.marklogic.semantics.sesame.MarkLogicRepository.getConnection(MarkLogicRepository.java:48) ~[marklogic-sesame-1.0.0-SNAPSHOT.jar!/:na]
at com.bericotechnologies.imc.rest.config.marklogic.MarkLogicRepositoryContext.getConnection(MarkLogicRepositoryContext.java:159) ~[imc-rest-rya-1.2.2-SNAPSHOT.jar!/:1.2.2-SNAPSHOT]
at com.bericotechnologies.imc.rest.config.marklogic.MarkLogicRepositoryContext$$EnhancerBySpringCGLIB$$2583623f.CGLIB$getConnection$3(<generated>) ~[imc-rest-rya-1.2.2-SNAPSHOT.jar!/:1.2.2-SNAPSHOT]
at com.bericotechnologies.imc.rest.config.marklogic.MarkLogicRepositoryContext$$EnhancerBySpringCGLIB$$2583623f$$FastClassBySpringCGLIB$$b7a669a3.invoke(<generated>) ~[imc-rest-rya-1.2.2-SNAPSHOT.jar!/:1.2.2-SNAPSHOT]
at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355) ~[spring-context-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at com.bericotechnologies.imc.rest.config.marklogic.MarkLogicRepositoryContext$$EnhancerBySpringCGLIB$$2583623f.getConnection(<generated>) ~[imc-rest-rya-1.2.2-SNAPSHOT.jar!/:1.2.2-SNAPSHOT]
at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory$2.getObject(AbstractBeanFactory.java:345) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.web.context.request.AbstractRequestAttributesScope.get(AbstractRequestAttributesScope.java:44) ~[spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:340) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:187) ~[spring-aop-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
at com.sun.proxy.$Proxy119.prepareTupleQuery(Unknown Source) ~[na:na]

**Comment by xquery** [comment]
thank you for this bug report, 

I believe we have addressed this issue (and other variations on the theme) but still in the process of doing longer term load testing before hand off to QA. Once this bug reverts to test, you will know when to hit develop branch to retest.

Keep the bug reports coming!

**Comment by cmatheus** [comment]
Jim,

can you tell what the "fix" label means?
does it mean there's a fix in place or that a fix is being worked on?
if the former is the fix in the "develop" branch? 
if the latter do you have a estimate of when it might be ready?

thanks for the effort on this,
Chris

**Comment by xquery** [comment]
'fix' means we are currently in the process of addressing this bug/task and barring some kind of issue likely to be included in the next release. 

When the bug switches to 'test' it will be available on develop branch, when it is closed then it should be included in the next release.

As a rule, we make no precise estimate on release tests though roughly I think the unit of  ~week(s) applies for when this will show up on develop branch.

**Comment by xquery** [comment]
Chris, before I commit the fix for this to develop branch I thought I would ask if you are able to provide a minimal test case (just in case we missed anything) ?

**Comment by cmatheus** [comment]
the person who has that code is out of the office until later this afternoon.  I'll ask him for it when he returns.

thanks.

**Comment by cmatheus** [comment]
1. conn = repository.getConnection();
2. conn.begin();
3. conn.close();
4. repository.getConnection();

Step 4 calls setIsolation(), which throws an exception because a transaction is active.

**Comment by xquery** [comment]
@srinathgit this is covered off by the isolation test you just added

**Comment by srinathgit** [comment]
Shipping the bug as the test runs successfully
