### ISSUE TITLE
Unable to close() connection when using user with only "rest-reader" privileges

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#320]
The issue happens when calling testReaderCon.close() and cache is not empty 

```
public test(){

        try{
            testReaderCon.prepareUpdate("CREATE GRAPH <abc>").execute();
            Assert.assertTrue(false);
        }
        catch(Exception e){
            Assert.assertTrue(e instanceof UpdateExecutionException);
        }


        final Statement st1 = vf.createStatement(john, fname, johnfname);

          try{
            testReaderCon.add(st1, vf.createURI("http://abc"));
        }
        catch(Exception e){
            Assert.assertTrue(e instanceof UpdateExecutionException);
        }
    testReaderCon.close();
}
```

```
com.marklogic.client.ForbiddenUserException: Local message: User is not allowed to apply resource at graphs. Server Message: You do not have permission to this method and URL.
    at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4629)
    at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3515)
    at com.marklogic.client.impl.JerseyServices.mergeGraphs(JerseyServices.java:5466)
    at com.marklogic.client.impl.GraphManagerImpl.mergeGraphs(GraphManagerImpl.java:342)
    at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performAdd(MarkLogicClientImpl.java:294)
    at com.marklogic.semantics.sesame.client.MarkLogicClient.sendAdd(MarkLogicClient.java:296)
    at com.marklogic.semantics.sesame.client.WriteCacheTimerTask.flush(WriteCacheTimerTask.java:150)
    at com.marklogic.semantics.sesame.client.WriteCacheTimerTask.forceRun(WriteCacheTimerTask.java:167)
    at com.marklogic.semantics.sesame.client.MarkLogicClient.sync(MarkLogicClient.java:151)
    at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.sync(MarkLogicRepositoryConnection.java:1366)
    at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.close(MarkLogicRepositoryConnection.java:131)

```

**Comment by xquery** [comment]
yes rest-reader can only read ... looks like I need to wrap up ForbiddenUserException exception ... nice catch

**Comment by grechaw** [comment]
Migrated to jira issue for rdf4j

https://pm.marklogic.com/browse/RDF4J-3

Closing this one in sesame as we're not planning another release.
