### ISSUE TITLE
RDFParse exception not thrown when adding malformed turtle file

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#65]
The exception stack trace seen below is thrown and not RDFParseException when adding malformed turtle file

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at graphs: Internal Server Error. Server Message: XDMP-DOCBADCHAR: xdmp:turtle($body, $options) -- Unexpected character found: '_' (0x005f) at :6:26 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4600)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3494)
	at com.marklogic.client.impl.JerseyServices.mergeGraph(JerseyServices.java:5429)
	at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:207)
	at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:193)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performAdd(MarkLogicClientImpl.java:246)
	at com.marklogic.semantics.sesame.client.MarkLogicClient.sendAdd(MarkLogicClient.java:138)
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.add(MarkLogicRepositoryConnection.java:500)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testAddMalformedLiteralsDefaultConfig(MarkLogicRepositoryConnectionTest.java:1207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by xquery** [comment]
for now should throw MarkLogicSesameException.

I would prefer that the java api client provide more accurate 'java' exceptions instead of exposing raw ML http server errors. This would avoid us mapping them independently in Sesame and Jena.

**Comment by srinathgit** [comment]
It still throws "com.marklogic.client.FailedRequestException" and not "MarkLogicSesameException".

**Comment by xquery** [comment]
reviewing this again ... this now throws an RDFException which is more appropriate then a MarkLogicSesameException

the following test (in MarkLogicExceptionsTest.java) works

```
    // https://github.com/marklogic/marklogic-sesame/issues/65
    @Test
    public void testAddMalformedTurtle() throws Exception {
        File inputFile = new File("src/test/resources/testdata/malformed-literals.ttl");
        String baseURI = "http://example.org/example1/";
        Resource context1 = conn.getValueFactory().createURI("http://marklogic.com/test/context1");
        exception.expect(RDFParseException.class);
        conn.add(inputFile, baseURI, RDFFormat.TURTLE, context1);
        conn.clear(context1);
    }
```

handing back to you for testing ... if you think we should do something different please comment and pass back to me.

**Comment by srinathgit** [comment]
The test below fails at "Assert.assertTrue(e instanceof RDFParseException);". The exception stack trace is as follows and it still throws a "FailedRequestException" not "RDFParseException".

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at graphs: Internal Server Error. Server Message: XDMP-DOCBADCHAR: xdmp:turtle($body, $options) -- Unexpected character found: '_' (0x005f) at :6:26 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4610)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3493)
	at com.marklogic.client.impl.JerseyServices.mergeGraph(JerseyServices.java:5435)
	at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:204)
	at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:189)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performAdd(MarkLogicClientImpl.java:292)
	at com.marklogic.semantics.sesame.client.MarkLogicClient.sendAdd(MarkLogicClient.java:219)
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.add(MarkLogicRepositoryConnection.java:970)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testAddMalformedLiteralsDefaultConfig(MarkLogicRepositoryConnectionTest.java:1858)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


	@Test
	public void testAddMalformedLiteralsDefaultConfig()
		throws Exception
	{
		try {
			testAdminCon.add(
					MarkLogicRepositoryConnectionTest.class.getResourceAsStream(TEST_DIR_PREFIX + "malformed-literals.ttl"),
					"", RDFFormat.TURTLE);
			fail("upload of malformed literals should fail with error in default configuration");
		}
		catch (Exception e) {
			e.printStackTrace();
			Assert.assertTrue(e instanceof RDFParseException);
		}
	}

**Comment by xquery** [comment]
ok thx for the clarification and test

**Comment by xquery** [comment]
PR #157 handles InputStream variant

**Comment by srinathgit** [comment]
Verified that RDFParseException is thrown.
