### ISSUE TITLE
Adding triples of format ntriples fails

### ISSUE THREAD

**Issue by srinathgit** [marklogic/marklogic-sesame#67]
Adding triples of format ntriples fails with exception. 
con.add(MarkLogicRepositoryConnectionTest.class.getResourceAsStream( "family-tree.nt"), "", 				RDFFormat.NTRIPLES, dirgraph);

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at graphs: Internal Server Error. Server Message: XDMP-DOCBADCHAR: xdmp:nquad($body, $options) -- Unexpected character found: '﻿' (0xfeff) at :1:0 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4600)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3494)
	at com.marklogic.client.impl.JerseyServices.mergeGraph(JerseyServices.java:5429)
	at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:207)
	at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:193)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performAdd(MarkLogicClientImpl.java:244)
	at com.marklogic.semantics.sesame.client.MarkLogicClient.sendAdd(MarkLogicClient.java:138)
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.add(MarkLogicRepositoryConnection.java:500)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testPrepareQuery1(MarkLogicRepositoryConnectionTest.java:1074)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by xquery** [comment]
can you provide or point me to triples data... we test this exact scenario and that works so need to understand the delta

**Comment by srinathgit** [comment]
Data:

<http://mydomain.org/resource/Joe> <http://dbpedia.org/ontology/parent> <http://mydomain.org/resource/John> .
<http://mydomain.org/resource/Joe> <http://dbpedia.org/ontology/parent> <http://mydomain.org/resource/Sue> .
<http://mydomain.org/resource/Joe> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
<http://mydomain.org/resource/Joe> <http://xmlns.com/foaf/0.1/name> "Joe"^^<http://www.w3.org/2001/XMLSchema#string> .

<http://mydomain.org/resource/John> <http://dbpedia.org/ontology/parent> <http://mydomain.org/resource/Tom> .
<http://mydomain.org/resource/John> <http://dbpedia.org/ontology/parent> <http://mydomain.org/resource/Mary> .
<http://mydomain.org/resource/John> <http://dbpedia.org/ontology/child> <http://mydomain.org/resource/Joe> .
<http://mydomain.org/resource/John> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
<http://mydomain.org/resource/John> <http://xmlns.com/foaf/0.1/name> "John"^^<http://www.w3.org/2001/XMLSchema#string> .

<http://mydomain.org/resource/Sue> <http://dbpedia.org/ontology/parent> <http://mydomain.org/resource/Tim> .
<http://mydomain.org/resource/Sue> <http://dbpedia.org/ontology/parent> <http://mydomain.org/resource/Amy> .
<http://mydomain.org/resource/Sue> <http://dbpedia.org/ontology/child> <http://mydomain.org/resource/Joe> .
<http://mydomain.org/resource/Sue> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
<http://mydomain.org/resource/Sue> <http://xmlns.com/foaf/0.1/name> "Sue"^^<http://www.w3.org/2001/XMLSchema#string> .

<http://mydomain.org/resource/Tom> <http://dbpedia.org/ontology/child> <http://mydomain.org/resource/John> .
<http://mydomain.org/resource/Tom> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .
<http://mydomain.org/resource/Tom> <http://xmlns.com/foaf/0.1/name> "Tom"^^<http://www.w3.org/2001/XMLSchema#string> .

Test:
	testAdminCon.add(MarkLogicRepositoryConnectionTest.class.getResourceAsStream(TEST_DIR_PREFIX + "family-tree.nt"), "",
				RDFFormat.NTRIPLES, dirgraph);

Exception:

com.marklogic.client.FailedRequestException: Local message: failed to apply resource at graphs: Internal Server Error. Server Message: XDMP-DOCBADCHAR: xdmp:nquad($body, $options) -- Unexpected character found: '﻿' (0xfeff) at :1:0 . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4600)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3494)
	at com.marklogic.client.impl.JerseyServices.mergeGraph(JerseyServices.java:5429)
	at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:207)
	at com.marklogic.client.impl.GraphManagerImpl.merge(GraphManagerImpl.java:193)
	at com.marklogic.semantics.sesame.client.MarkLogicClientImpl.performAdd(MarkLogicClientImpl.java:244)
	at com.marklogic.semantics.sesame.client.MarkLogicClient.sendAdd(MarkLogicClient.java:138)
	at com.marklogic.semantics.sesame.MarkLogicRepositoryConnection.add(MarkLogicRepositoryConnection.java:500)
	at com.marklogic.sesame.functionaltests.MarkLogicRepositoryConnectionTest.testAddDifferentFormats(MarkLogicRepositoryConnectionTest.java:1075)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by srinathgit** [comment]
I am able to add ntriples. There was an issue with the data that I used earlier (seems like it was malformed). I checked with a correctly formed ntriple file and I was able to add them fine.

**Comment by xquery** [comment]
ok, mystery solved, though it begs the question if we should wrap error messages from java api client ?

**Comment by srinathgit** [comment]
I have filed an enhancement request for a similar issue . We expect to wrap it and throw an RDFException.

**Comment by srinathgit** [comment]
Closing this case as all the methods that throw incorrect exceptions is being tracked in Issue 73 and that enhancement has been pushed to  marklogic-sesame-1.0.1
